import { NextRequest, NextResponse } from "next/server";
import prisma from "@/lib/db";

// GET /api/documents — list documents
export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const orgId = searchParams.get("orgId") || "default";
  const dealId = searchParams.get("dealId");

  try {
    const where: Record<string, unknown> = {};
    if (dealId) {
      where.dealId = dealId;
    } else {
      // Use relation filter — single query, no intermediate deal ID load
      where.deal = { organizationId: orgId };
    }

    const documents = await prisma.document.findMany({
      where: where as any,
      include: { deal: true, template: true },
      orderBy: { createdAt: "desc" },
    });
    return NextResponse.json({ documents });
  } catch (error) {
    return NextResponse.json({ error: "Failed to fetch documents", detail: String(error) }, { status: 500 });
  }
}

// POST /api/documents — generate a document from template
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { dealId, templateId, type = "OTHER", orgId = "default" } = body;

    // Fetch deal with property, seller, buyer
    const deal = await prisma.deal.findFirst({
      where: { id: dealId, organizationId: orgId },
      include: {
        property: true,
        seller: true,
        buyer: true,
      },
    });

    if (!deal) {
      return NextResponse.json({ error: "Deal not found" }, { status: 404 });
    }

    let content = "";
    let templateName = "Custom Document";

    if (templateId) {
      const template = await prisma.documentTemplate.findFirst({
        where: { id: templateId, organizationId: orgId },
      });
      if (template) {
        templateName = template.name;
        // Replace template variables with deal data
        content = template.content
          .replace(/\{\{dealTitle\}\}/g, deal.title)
          .replace(/\{\{propertyAddress\}\}/g, deal.property?.street || "")
          .replace(/\{\{propertyCity\}\}/g, deal.property?.city || "")
          .replace(/\{\{propertyState\}\}/g, deal.property?.state || "")
          .replace(/\{\{propertyZip\}\}/g, deal.property?.zip || "")
          .replace(/\{\{sellerName\}\}/g, deal.seller ? `${deal.seller.firstName} ${deal.seller.lastName}` : "N/A")
          .replace(/\{\{buyerName\}\}/g, deal.buyer ? `${deal.buyer.firstName} ${deal.buyer.lastName}` : "To be assigned")
          .replace(/\{\{offerPrice\}\}/g, deal.offerPrice ? `$${deal.offerPrice.toLocaleString()}` : "")
          .replace(/\{\{contractPrice\}\}/g, deal.contractPrice ? `$${deal.contractPrice.toLocaleString()}` : "")
          .replace(/\{\{assignmentFee\}\}/g, deal.assignmentFee ? `$${deal.assignmentFee.toLocaleString()}` : "")
          .replace(/\{\{emd\}\}/g, deal.emd ? `$${deal.emd.toLocaleString()}` : "")
          .replace(/\{\{closingDate\}\}/g, deal.closingDate ? new Date(deal.closingDate).toLocaleDateString() : "")
          .replace(/\{\{arv\}\}/g, deal.property?.arv ? `$${Number(deal.property.arv).toLocaleString()}` : "")
          .replace(/\{\{repairCost\}\}/g, deal.property?.repairCost ? `$${Number(deal.property.repairCost).toLocaleString()}` : "")
          .replace(/\{\{beds\}\}/g, deal.property?.beds?.toString() || "")
          .replace(/\{\{baths\}\}/g, deal.property?.baths?.toString() || "")
          .replace(/\{\{sqft\}\}/g, deal.property?.sqft?.toLocaleString() || "");
      }
    }

    // If no template, generate a basic contract
    if (!content) {
      content = `
        <h1>${type === "ASSIGNMENT_CONTRACT" ? "Assignment of Contract" : "Purchase Agreement"}</h1>
        <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
        <p><strong>Property:</strong> ${deal.property?.street}, ${deal.property?.city}, ${deal.property?.state} ${deal.property?.zip}</p>
        <p><strong>Seller:</strong> ${deal.seller ? `${deal.seller.firstName} ${deal.seller.lastName}` : "N/A"}</p>
        <p><strong>Buyer:</strong> ${deal.buyer ? `${deal.buyer.firstName} ${deal.buyer.lastName}` : "To be assigned"}</p>
        <p><strong>Contract Price:</strong> $${(deal.contractPrice || deal.offerPrice || 0).toLocaleString()}</p>
        <p><strong>Assignment Fee:</strong> $${(deal.assignmentFee || 0).toLocaleString()}</p>
        <p><strong>EMD:</strong> $${(deal.emd || 0).toLocaleString()}</p>
        <p><strong>Closing Date:</strong> ${deal.closingDate ? new Date(deal.closingDate).toLocaleDateString() : "TBD"}</p>
        <hr />
        <p><em>Generated by WholeCRM on ${new Date().toISOString()}</em></p>
      `.trim();
    }

    const document = await prisma.document.create({
      data: {
        dealId,
        templateId: templateId || null,
        name: `${type.replace(/_/g, " ")} — ${deal.title}`,
        type,
        content,
      },
      include: { deal: true, template: true },
    });

    return NextResponse.json(document, { status: 201 });
  } catch (error) {
    return NextResponse.json({ error: "Failed to generate document", detail: String(error) }, { status: 500 });
  }
}
